# Generated by Django 4.2.11 on 2024-05-20 12:03

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familyasi', models.CharField(max_length=255)),
                ('t_sana', models.DateField()),
                ('tel', models.CharField(max_length=20)),
                ('yashash_manzili', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stars', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uylar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holati', models.TextField()),
                ('yashash_maydoni', models.CharField(max_length=255)),
                ('xonalar_soni', models.BigIntegerField()),
                ('joylashuvi', models.CharField(max_length=255)),
                ('mijoz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.mijoz')),
            ],
        ),
        migrations.CreateModel(
            name='Vazifalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vazifa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Xususiyati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narxi', models.CharField(max_length=255)),
                ('sana', models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 20, 17, 3, 30, 750106))),
                ('defaultimage', models.ImageField(default='defaulthome.jpg', upload_to='')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.stars')),
                ('uy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.uylar')),
                ('vazifasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.vazifalar')),
            ],
        ),
        migrations.CreateModel(
            name='UyRasmlari',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(default='default.jpg', upload_to='')),
                ('xususiyat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.xususiyati')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.uylar')),
            ],
        ),
    ]
