# Generated by Django 4.2.11 on 2024-04-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=255)),
                ('familyasi', models.CharField(max_length=255)),
                ('t_sana', models.DateField()),
                ('tel', models.CharField(max_length=20)),
                ('yashash_manzili', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stars', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uylar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holati', models.TextField()),
                ('yashash_maydoni', models.CharField(max_length=255)),
                ('xonalar_soni', models.BigIntegerField()),
                ('joylashuvi', models.CharField(max_length=255)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.mijoz')),
            ],
        ),
        migrations.CreateModel(
            name='Vazifalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vazifa', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xususiyati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vazifasi_id', models.CharField(max_length=255)),
                ('narxi', models.CharField(max_length=255)),
                ('sana', models.DateTimeField()),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.stars')),
                ('uy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.uylar')),
            ],
        ),
        migrations.CreateModel(
            name='UyRasmlari',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(default='default.jpg', upload_to='')),
                ('uy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.uylar')),
            ],
        ),
    ]
