# Generated by Django 4.2.11 on 2024-04-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vazifalar',
            name='vazifa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='xususiyati',
            name='vazifasi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_1.vazifalar'),
        ),
    ]
