# Generated by Django 4.2.11 on 2024-04-24 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_1', '0002_alter_vazifalar_vazifa_alter_xususiyati_vazifasi_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xususiyati',
            old_name='vazifasi_id',
            new_name='vazifasi',
        ),
        migrations.RemoveField(
            model_name='uyrasmlari',
            name='uy',
        ),
        migrations.AddField(
            model_name='uyrasmlari',
            name='xususiyat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page_1.xususiyati'),
            preserve_default=False,
        ),
    ]
