# Generated by Django 4.2.11 on 2024-04-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_1', '0003_rename_vazifasi_id_xususiyati_vazifasi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xususiyati',
            name='defaultimage',
            field=models.ImageField(default='defaulthome.jpg', upload_to=''),
        ),
    ]
