# Generated by Django 4.2.11 on 2024-05-08 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_1', '0004_xususiyati_defaultimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xususiyati',
            name='sana',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 8, 17, 9, 45, 916599)),
        ),
    ]
