# Generated by Django 4.2.11 on 2024-05-14 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_1', '0005_alter_xususiyati_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xususiyati',
            name='sana',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 14, 13, 39, 36, 33316)),
        ),
    ]
