# Generated by Django 4.2.11 on 2024-05-15 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_1', '0007_alter_xususiyati_sana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uylar',
            old_name='mijoz',
            new_name='клиент',
        ),
        migrations.RenameField(
            model_name='uylar',
            old_name='holati',
            new_name='положениедел',
        ),
        migrations.AlterField(
            model_name='xususiyati',
            name='sana',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 5, 15, 17, 18, 58, 699856)),
        ),
    ]
